# Ingress
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tds-devops-jenkins-ingress
  namespace: tds-devops
spec:
  ingressClassName: public-iks-k8s-nginx
  rules:
  - host: tds-devops-jenkins.tdse.now.hclsoftware.cloud
    http:
      paths:
      - backend:
          service:
            name: tds-devops-jenkins
            port:
              number: 8080
        path: /
        pathType: Prefix
